### ISSUE TITLE
Add a routes cli command

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#103]
that, like Rails, displays all routes that Denali responds to.

**Comment by acorncom** [comment]
I'm happy to work on this, is this something we want?

**Comment by davewasmer** [comment]
Yea, could definitely be helpful 👍

**Comment by knownasilya** [comment]
I think we discussed this in regards to alternate router definitions, specifically via decorators.

**Comment by davewasmer** [comment]
Yea - I think regardless of whether routes are specified inline in actions via decorators, or via the current approach of a router map file, I think this command would still be useful.

**Comment by knownasilya** [comment]
I like to edit my comments, if you haven't noticed. 🍤  <= was supposed to have been a shrug, but this was the closest..
