### ISSUE TITLE
Remove extraneous text on the home page

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#106]
I'm not seeing where the homepage text is, so thought I'd send this over.  
![screen shot 2016-09-26 at 10 46 04 am](https://cloud.githubusercontent.com/assets/802505/18843494/82d3054e-83d6-11e6-8fee-62f94be051f2.png)

Highlighted text should be removed to make that sentence read more crisply

**Comment by davewasmer** [comment]
Homepage text is on the docs branch, inside `src/pages`: https://github.com/denali-js/denali/blob/docs/src/pages/index.html (for future reference). That folder is for files that are more or less "static", i.e. don't correspond to docs generated from code. So the homepage, an about page, that kind of stuff.
