### ISSUE TITLE
Fix record serialization errors

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#109]
This may be an issue with the ember-help-wanted-backend setup I have here, but I'm using the latest code from https://github.com/denali-js/denali/pull/97 and latest default blueprints, so I don't think it is https://github.com/ember-learn/ember-help-wanted-backend/pull/5  

From what it looks like, this is a Denali issue, not an ORM adapter issue.  It was time for me to get off 5-10 min ago, so putting this here in case someone else wants to fix it for me ;-)  The above PR should have everything needed to replicate this error ...

```
[2016-09-28T00:06:30.133Z] ERROR - AssertionError: Attempted to serialize a record (<Issue:-new->) without an id, but the JSON-API spec requires all resources to have an id.
    at Function.renderRecord (./denali/lib/data/serializers/json-api.js:178:5)
    at ./denali/lib/data/serializers/json-api.js:93:21
    at Array.map (native)
    at Function.renderPrimaryArray (./denali/lib/data/serializers/json-api.js:91:31)
    at Function.renderPrimary (./denali/lib/data/serializers/json-api.js:70:12)
    at Function.serialize (./denali/lib/data/serializers/json-api.js:49:10)
    at ListIssues.render (./tmp/denali/lib/runtime/action.js:189:34)
```

**Comment by davewasmer** [comment]
I'll dig in when I have a minute, but at first glance, this is coming from the JSON-API serializer, so a couple different things could be happening:

* Are you sure the record you are attempting to render has an ID? I'm not at home in SQL, but it looks like the `id` field is not autoincrementing? If so, assuming node-orm2 isn't setting an ID (which seems like a potentially bad idea), that might be the problem.
* If there is an ID on the record immediately before you return in from your action, it's possible there's a breakdown at the model/orm adapter layer. The serializer will ask the model for it's ID, and Denali's model class uses a getter to proxy that to the adapter's `idFor(model)` method. So the adapter could be failing to return an ID, and/or the model could be failing to call the adapter method as expected.

**Comment by acorncom** [comment]
@davewasmer Turns out my record didn't have an ID (you're right, I hadn't setup an auto increment, :fail:).  This whole issue goes away with an accurate DB 😀 Sorry about the noise.
