### ISSUE TITLE
Docs Build: Prevent local tags from building in docs/api

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#121]
Currently if you tag it locally and do a docs build, those tags will end up on the site. Only tags on github should be built I think.

**Comment by davewasmer** [comment]
I'll take a stab at getting travis to deploy the docs on each successful build, which should alleviate the need to deploy from our local machines, and would make this problem obsolete.

**Comment by davewasmer** [comment]
Docs should be deploying from travis now (finally). Closing, but feel free to reopen if you think we need more.
