### ISSUE TITLE
Add a test dummy app blueprint to add-on generation

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#126]
So that add-on authors are setup with the ability to do tests by default.  Looks like we've got the stub for that logic here (https://github.com/denali-js/denali/blob/master/lib/test/setup-app.js#L18-L20) but there is no corresponding blueprint to when an add-on is first created ...

**Comment by davewasmer** [comment]
This should be resolved on master now. You can use Denali itself for an example :wink:. Feel free to reopen/refile if we are still missing something though.
