### ISSUE TITLE
Model#eachAttribute leaks _attributesCache state

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#127]
When I've got two models (an `ApplicationModel` and an `Issue` model) as seen in the `ember-help-wanted-backend` app, the cache check here (https://github.com/denali-js/denali/blob/master/lib/data/model.js#L345) properly passes the first time I run through the `ApplicationModel` but is set to `[]` when running through `eachAttribute` on the `Issue` model.

Seems like that's because the `ApplicationModel` prototype (which `Issue` "inherits" from) already had that value set.  Not sure how to fix this issue (would be happy to send in a PR with some guidance).

I've temporarily changed what my Issue model inherits from and dodged this bug ...

**Comment by davewasmer** [comment]
Ah yea. Maybe try updating the conditional to check if it `hasOwnProperty` first? That should return false if the child class doesn't have it defined but the parent class does. So something like:

```js
if (!this.hasOwnProperty('_attributesCache') || this._attributesCache == null) {
```

I think that should do it, unless ES6 does something different than usual with prototypical inheritance on the classes themselves.

**Comment by acorncom** [comment]
If we go back to the idea of abstract models being a thing (as discussed here: https://github.com/denali-js/denali-node-orm2/pull/1#discussion_r82338650) along with filtering them out at the ORM level, I believe this bug would go away ...  Should I send this fix in as well or close this and go the `abstract` route?

**Comment by davewasmer** [comment]
We'll probably need to fix this regardless. Just because a model is abstract doesn't mean you'll never call `eachAttribute` on it, which would end up hitting this bug again.
