### ISSUE TITLE
Ensure responding with JSON-API content-type header is allowed

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#141]
By default Denali responds with a content type of 'application/json' As mentioned in the spec, a JSON-API response content type must be: `Content-Type: application/vnd.api+json`

Looks like this can be tweaked at a config level (although there are some todos about the config in code).

Don't have time ATM to test this thoroughly but will aim to come back to this later ...

**Comment by knownasilya** [comment]
Shouldn't it be the default for the JSON API serializer?

**Comment by davewasmer** [comment]
This should be fixed now that serializers can set the content type header.
