### ISSUE TITLE
[API Question] Is the request part of Action public API? 

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#143]
As part of `Action`'s constructor (https://github.com/denali-js/denali/blob/master/lib/runtime/action.js#L127-L132) the request object is passed in.  But we don't currently document that it's a public property.  I think it should be (as for some actions users **will** need access to headers, etc) but wanted to confirm before I lean on it too heavily.

Happy to send in a PR to add the appropriate docs if we think it is ...

**Comment by davewasmer** [comment]
Yes, it should be public, but perhaps with the caveat that it won't always be defined? One thing we should plan for is socket support, and one of the things we are considering is allowing socket messages to trigger actions. So I get nervous about guaranteeing `action.request` will always exist, because that ties our hands when it comes to sockets.

**Comment by knownasilya** [comment]
Maybe http actions should be subclassed just for the future support? So then request is defined on the http action, but not on the general action class.

**Comment by davewasmer** [comment]
Well, I'm not sure we necessarily will go that way, so I'm hesitant to preemptively subclass action.

We could document it as public for now, but include a note in the docs that it's likely to change before 1.0?

**Comment by acorncom** [comment]
> We could document it as public for now, but include a note in the docs that it's likely to change before 1.0?

We could ...  Not a huge fan of that but seems ok.  My main question here was related to how to tie in the middleware I was using (which acts much more like an action at the Node level) and wondering if I should try to get it access to the request / response objects within an Action itself.  I'll send over a prototype adjustment to the router that's been floating around my head that might solve my issue though without needing this ...
