### ISSUE TITLE
Refactor mocha for ava

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#162]
Not stuck on ava, but the goal is to use something more future focused. 

Here's an example refactor https://github.com/zeit/now-client/pull/50

**Comment by davewasmer** [comment]
Could you provide a brief summary of why you think we should move off Mocha? Not opposed to something new, but I'd like to make we understand the tradeoffs before we invest time in it.

**Comment by knownasilya** [comment]
What we gain is listed here https://github.com/avajs/ava#why-ava (didn't want to rewrite it any worse lol).

**Comment by davewasmer** [comment]
Done!
