### ISSUE TITLE
Explore sourcemap support

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#164]
Looking at https://github.com/evanw/node-source-map-support#node-support I see the following comment.

> Note: if you're using babel-register, it includes source-map-support already.

We use both; babel-register is installed in app/addon blueprints and sourcemap support, so this needs to be figured out. According to @davewasmer we want to remove `babel-register` since it's not production ready.

Also, sourcemaps currently don't work with `denali server --debug`, see the issue in node https://github.com/nodejs/node/issues/8369

---

**Status**: 🚫  Blocked by https://github.com/nodejs/node/issues/8369
### Action Items
- [ ] Remove babel-register
- [ ] Make sure babel transpile is setup for sourcemaps (sourceMaps: 'inline')

**Comment by davewasmer** [comment]
@knownasilya - based on the recent updates to the linked Node issue, it sounds like the latest Node + Chrome Canary supports this now. Plus, denali is now compiled via typescript and includes inlined sourcemaps and sources.

Is that all we need for this to work? Is there anything else?

**Comment by knownasilya** [comment]
Sounds good to me.
