### ISSUE TITLE
Add handling of multiple serializers in Action when using action responder system

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#169]
Denali has the ability to specify a serializer using a simple string as follows:

``` javascript
serializer = 'json-api'
```

Denali also has the ability to respond differently based on the `Accept` header using methods named `respondWith<TypeNameHere>` (https://github.com/denali-js/denali/blob/master/lib/runtime/action.js#L251-L277).

A problem can occur though where the simple serializer declaration above could conflict with the response (i.e. our default serializer is JSON-API but the client requested data in XML).  Although we want to respond using `respondWithXml`, we don't want the response to run through the JSON-API serializer (but would prefer to use the theoretical xml serializer).

To make this work, we'd like to see the `serializer` property accept three options:

``` javascript
serializer = false; // supported currently

serializer = 'json-api'; // supported currently

serializer = { xml: 'xml', 'json-api': 'json-api' }; // advanced use case, unlikely to be used often
```

Doing this gives folks some basic escape valves without having to specify their serializer on a per `respondWithMethod` basis (allowing easier inheritance across a complex API)

**Comment by davewasmer** [comment]
Closing this in favor of #170 - this feels like a symptom of the problem described there.
