### ISSUE TITLE
denali-fastboot addon

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#186]
An official addon that integrates [fastboot](https://ember-fastboot.com/) support into denali.

Probably with https://github.com/ember-fastboot/fastboot-express-middleware

**Comment by acorncom** [comment]
If we use https://github.com/ember-fastboot/fastboot-express-middleware it looks like we leave Denali users in a bit of a bind re how to handle new Ember app deploys (especially annoying in clustered mode). But if we use the full Express server we're almost guaranteed to run into conflicts with Fastboot's Express server. Theoretically you can swap out the httpSeever in Fastboot but ...

**Comment by knownasilya** [comment]
We could just use fastboot directly.

**Comment by davidpett** [comment]
Is this mostly to keep the ember app and denali app served from the same server? I almost prefer to keep them separate.

**Comment by davewasmer** [comment]
Yes. The idea is for this to be an addon - you certainly don't have to combine them.

However, having first class support via an addon would allow you to do things like use Denali to inject some preloaded data into the fastboot served page, without needing to hit your own Denali API over the network from a separate fastboot server.

**Comment by davewasmer** [comment]
Closing in favor of the RFA on the forums: http://discuss.denalijs.org/t/request-for-addon-ember-fastboot/46
