### ISSUE TITLE
Seeing errors related to ava when running tests in add ons / app

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#197]
I'm seeing the below error when running `denali test` (which is `npm link`ed in) for either an add-on or an app:

```
$ denali test

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Babel                                         | 2592ms              
Babel                                         | 2112ms              
Babel                                         | 1275ms              
LintTree                                      | 955ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (16)                                    | 7821ms (488 ms)     
LintTree (12)                                 | 1346ms (112 ms)     

Error: spawn ./node_modules/.bin/ava ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

If it's useful:

| Tool | Version |
| --- | --- |
| Node | v6.6.0 |
| NPM | 3.10.3 |
| Yarn | 0.16.1 |

**Comment by davewasmer** [comment]
Ah - ava isn't listed as a dependency on the app/addon blueprint package.json, so it's executable isn't floated up to node_modules/.bin when symlinked in.

We can either add ava as a dep for apps & addons, or try to make the test command smart enough to detect this situation and dive into the denali nested node_modules/.bin folder for the executable.

**Comment by davewasmer** [comment]
In this particular case, I'm realizing ava should probably be in the devDeps on the consuming app, since it's directly imported by the consuming app's test files.

**Comment by davewasmer** [comment]
This should be resolved now - mind checking @acorncom?

**Comment by acorncom** [comment]
@davewasmer Yep, it's fixed once blueprints have been updated.  Closing
