### ISSUE TITLE
Remove autoLoadExtensions?

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#198]
Right now, Denali will automatically attempt to load almost _all_ files found in `app/` into the container, for the app and each addon.

That includes non-js/json files, like text and html files, as long as their [file extension is in `addon.autoLoadExtensions`](https://github.com/denali-js/denali/blob/master/lib/runtime/addon.js#L103).

This feature (loading non-js files) pre-dates our current broccoli build process. It was originally designed with use cases like denali-mailer in mind, so that non-js files would still be loaded into the container such that the consuming app could reference them without their addon namespace (i.e. denali-mailer could include `app/mailers/default.html`, and the consuming app could then reference that via `container.lookup('mailers/default.html')` instead of `fs.readFileSync(pathToMailerAddon)`, allowing the consuming app to potentially override the denali-mailer supplied `default.html` without changing the lookup code).

However, now that we have the broccoli build process, the better approach for denali-mailer's use case is to precompile the templates during the build to avoid that performance hit at runtime. That removes the need to autoload HTML files, since they precompile into JS template files.

With that solution in mind, I'm having a hard time imagining a use case for loading non-js files into the container that isn't better solved by precompiling into JS files via a build step.

So - should we just drop autoLoadExtensions, and only load JS/JSON files into the container?

**Comment by davewasmer** [comment]
cc @acorncom @knownasilya @sivakumar-kailasam

**Comment by sivakumar-kailasam** [comment]
LGTM, if someone requests this as a feature we can always let them override via per app/addon config.

**Comment by davewasmer** [comment]
@sivakumar-kailasam true, but that would require overriding `loadApp()` in their `app/addon.js`, which is a pretty low-level monkey patch. If there's legitimate use cases that I'm missing, I think we should hesitate to remove this (or at least have a plan to address those).

**Comment by sivakumar-kailasam** [comment]
I can't really think of other uses which can't be solved with a broccoli transformation. So I guess we're clear to remove this as a feature/config.

**Comment by knownasilya** [comment]
Also fine with removing it. At the moment I can't think of any use for those types. Even css could be converted to js.

**Comment by acorncom** [comment]
The CSS use case (for email templates) seems to be the only thing we might want to load up. But broccoli transforms sound like the way to go there ... Let's take it out
