### ISSUE TITLE
Re-enable yarn installs in tests

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#202]
At the moment, yarn doesn't seem to support concurrent installs (yarnpkg/yarn#1275). Because ava runs tests in parallel, this means we are currently using the `--use-npm` flag in our tests. Once concurrent installs are supported, we should remove the `--use-npm` flag usage from Denali's tests to take advantage of yarn's performance.

**Comment by knownasilya** [comment]
Can we get this flag for `denali new` as well, also is it documented?

**Comment by davewasmer** [comment]
It's already there on [the app blueprint](https://github.com/denali-js/denali/blob/master/blueprints/app/index.js#L27), and documented to the extent that a description for the arg exists, but it looks like the new command doesn't print args when `--help` is passed in.

**Comment by knownasilya** [comment]
Yeah, probably what I was seeing.

**Comment by acorncom** [comment]
@davewasmer Per https://github.com/yarnpkg/yarn/issues/1275#issuecomment-256649947 it looks like we could manually specify a cache folder per test. Would that help speed up builds?

**Comment by davewasmer** [comment]
It probably would slightly - from what I understand, yarn is faster than npm even in a cold `yarn install` scenario, thanks to the way it resolves the entire dependency and then fetches the packages, rather than waiting till the packages download to resolve _their_ dependencies.

However, we lose a big perf gain, since each yarn command can't use the cache of the others.

I'm open to switching to that approach, but we would need to track and cleanup those yarn cache dirs. Simply adding a `--use-npm` flag was a quicker fix, especially since I didn't see any confirmation that the separate yarn cache dirs actually works 100%. But if anyone feels up to implementing and testing that solution, I'm happy to merge it.

**Comment by davewasmer** [comment]
This is enabled now.
