### ISSUE TITLE
Failing app acceptance test in an app using integration test from blueprints

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#206]
In the `ember-help-wanted-backend` app, I'm working on adding in integration tests with the new `AppAcceptanceTest` class.  I'm using a duplicate of the app blueprint integration test but it's failing in my app:

```
   1. integration › issues-test › GET / > should return a welcome message
   failed with "Cannot find module 'package.json'"
      new AppAcceptanceTest (./Sites/open-source/ember-learn/ember-help-wanted-backend/dist/node_modules/denali/lib/test/app-acceptance.js:43:15)
    _callee$ (issues-test.js:21:19)
    tryCatch (./Sites/open-source/ember-learn/ember-help-wanted-backend/node_modules/regenerator-runtime/runtime.js:62:40)
    GeneratorFunctionPrototype.invoke [as _invoke] (./Sites/open-source/ember-learn/ember-help-wanted-backend/node_modules/regenerator-runtime/runtime.js:336:22)
    GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (./Sites/open-source/ember-learn/ember-help-wanted-backend/node_modules/regenerator-runtime/runtime.js:95:21)
    step (issues-test.js:11:183)
    issues-test.js:11:437
    Test.<anonymous> (issues-test.js:11:99)
    Test.fn (issues-test.js:40:17)
    _combinedTickCallback (internal/process/next_tick.js:67:7)
    process._tickCallback (internal/process/next_tick.js:98:9)
```

The file in question [can be seen here](https://github.com/ember-learn/ember-help-wanted-backend/blob/getting-webhook-receiving/test/integration/issues-test.js#L1-L8) and the corresponding blueprint that I was copying [is here](https://github.com/denali-js/denali/blob/master/blueprints/app/files/__name__/test/integration/index-test.js)

**Comment by knownasilya** [comment]
Ran into this too

**Comment by davewasmer** [comment]
@acorncom any chance you could try this again against master? I pushed some fixes for the app acceptance test helper yesterday that I think might fix this.

**Comment by davewasmer** [comment]
Closing from lack of activity. If you can reproduce against latest, feel free to reopen
