### ISSUE TITLE
Fix security vulnerability warnings

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#209]
When running tests against Denali, I'm getting the following notice:

```
WARNING: Some packages in your package.json may have security vulnerabilities:
*** minimatch@2.0.10 ***
Found in: denali@0.0.13 => broccoli@0.16.9 => findup-sync@0.2.1 => glob@4.3.5 => minimatch@2.0.10
```

**Comment by acorncom** [comment]
A naive update to `broccoli@1.0.0-beta.7` (which doesn't contain the needed update to `findup-sync` but gets us closer) ends up breaking building:

```
TypeError: Cannot read property 'directory' of undefined
    at Project._finishBuild (./Sites/open-source/denali-js/denali/lib/cli/project.js:143:25)
    at ./Sites/open-source/denali-js/denali/lib/cli/project.js:45:14
    at tryCatch (./Sites/open-source/denali-js/denali/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
```

The changes introduced here seem to be what broke us: https://github.com/broccolijs/broccoli/commit/899a227f1cb2f9fca6ea5bff50571d162a59bbf6

**Comment by davewasmer** [comment]
Yea, broccoli 1.x has some sizable breaking changes in the API. I remember trying to upgrade a _while_ ago, but there was some plugin we were using that wasn't 1.x compatible and I didn't feel like rewriting it. I'd love to upgrade though ...

Another thing - it's a bummer that nsp doesn't allow you to ignore warnings by dependency. They only let you ignore specific warnings, regardless of where they appear in the dependency tree. In this case, the warning is about a DDOS vulnerability, but the vulnerable package is only used by broccoli, which is only at build time, so it doesn't matter. But nsp doesn't let you say "ignore vulnerabilities resulting from this dependency (i.e. broccoli)" - you can only say "ignore this vulnerability everywhere", which means if it appears in a runtime dependency (where it would actually be a problem) it would be ignored there too.

We could potentially add our own API (i.e. `config.nsp.ignoredDependencies`) that would simply not print errors from those packages ...
