### ISSUE TITLE
Print available addon blueprints via `denali g -h`

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#222]
I had this in my PR, but we never carried it over after the build rewrite. See code here: https://github.com/denali-js/denali/pull/97/files#diff-3774230457e07064462faa656c14da5dR93

**Comment by davewasmer** [comment]
Derp, sorry about that.

A bit swamped at the moment (triaging all those other bugs you filed :wink: and working on denali-auth). I'll label this as help-wanted - should be pretty straightforward to port that code over again.

**Comment by davewasmer** [comment]
This should work now with denali-cli
