### ISSUE TITLE
Request times out too soon when using `--debug`

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#224]
Timeout is 30 seconds.

I'd assume that requests should be long running when debugging so you can debug 👍

**Comment by davewasmer** [comment]
Is this a testing timeout? Or just when running `denali serve`?

**Comment by knownasilya** [comment]
`denali serve`

**Comment by davewasmer** [comment]
What are you using to make the request? Any chance the client is killing the connection?

I'm not sure what would be killing the request after 30 seconds. Node's HTTP server has a default timeout of 2 minutes, which we don't mess with. Other than that, I can't think of anything that would be killing the connection.

Does the connection drop while the debugger is paused? If so, that would point to client or OS level timeouts - Node can't kill the connection if it's paused.

**Comment by knownasilya** [comment]
Hum, I'm using https://httpie.org/ and yes you are correct it has a default of 30s..
