### ISSUE TITLE
Denali CLI errors on first usage

### ISSUE THREAD

**Issue by cafreeman** [denali-js/denali#237]
Just installed Denali and received the following error when I tried to scaffold up a new app:

```
> denali new blog
/Users/cf_frontside/.nvm/versions/node/v6.9.1/lib/node_modules/denali/commands/index.js:1
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at loader (/Users/cf_frontside/.nvm/versions/node/v6.9.1/lib/node_modules/denali/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/cf_frontside/.nvm/versions/node/v6.9.1/lib/node_modules/denali/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cf_frontside/.nvm/versions/node/v6.9.1/lib/node_modules/denali/bin/denali:31:3)
```

It seems like this may be a regression back to the bug originally reported in https://github.com/denali-js/denali/issues/180

**Comment by knownasilya** [comment]
What if we required latest node 7.x and drop babel? Just a thought @davewasmer, since the build stuff seems to be holding everything back.

**Comment by davewasmer** [comment]
@knownasilya - I'm not sure that's the best approach. The build stuff is holding things back because it's fundamentally hard, but that means its the kind of problem Denali should be solving. In the same way that Ember CLI solves the build process for client side apps (and is itself complex as a result), Denali should aim to solve these common, shared problems.

The build process is necessary in the first place because, with the increasing popularity of Typescript, the continuing evolution of the JS language, and underlying engine performance considerations (i.e. V8's implementation of the spread operator [is 24x slower than the babel transpiled ES5 version](http://kpdecker.github.io/six-speed/)), there is no "finish line" to cross here. For the forseeable future, _some_ degree of transpilation will be needed.

@cafreeman - sorry you ran into a bug on the first run, and apologies for the delayed response here (holidays). I'll dig into it first chance I get, and get back to you.

**Comment by knownasilya** [comment]
@davewasmer I totally agree with you 👍 and think that it's necessary, but was suggesting putting it on the back burner at least for now.

I haven't had fun trying to get server side setups working well with babel + test + coverage + sourcemaps + etc.. so Denali solving that is huge, and like you said, we will always be transpiling as long as the web exists..

**Comment by acorncom** [comment]
@davewasmer any chance we could move the build work off the main master branch so folks can continue experimenting with the rest of Denali that is more stable? I believe I remember you mentioning needing to publish versions to test things ... (would that be possible to do with rc-type versions that don't get used automatically by npm?)

**Comment by davewasmer** [comment]
I appreciate that the instability is frustrating right now - trust me, I want it resolved more than most :wink:.

Unfortunately, the earlier approach to the build process had several nasty edge cases, and flaky test failures. You're welcome to trying pinning to those versions if you got it working - the build process shouldn't really affect any of the runtime APIs, so you could try to stay in the "shelter" of those earlier versions until the build is sort out. But there's no easy way to separate runtime Denali from the build process, so there's no real "third way" here that lets folks experiment with Denali in the meantime.

As far as branching and/or using rc version tags - I could see the value here if we had a list of non-build-related fixes and improvements waiting that were being mixed together with the unstable build changes. Using a branch / rc tag would help us ship that work while figuring out the build.

But unfortunately, at this point, the only significant work happening on Denali is on the build process. There is no queue of additional work waiting for a stable release to make it out. So taking that, plus the fact that branch / rc tags introduce non-trivial workloads to maintain them, I'm not sure that's a valuable tradeoff at the moment.

**Comment by acburdine** [comment]
This should be fixed by the CLI extraction right?

**Comment by davewasmer** [comment]
Should be - I'm closing for now. @cafreeman - if you still run into this, feel free to drop a comment and we can reopen.

**Comment by steveszc** [comment]
I just started messing around with Denali. It built and ran fine locally... but when I tried to deploy to Heroku I got this error. I tried bumping my node version on heroku to 7.10 and it didnt seem to help.
```
(function (exports, require, module, __filename, __dirname) { import sourcemaps from 'source-map-support';
SyntaxError: Unexpected token import
```

**Comment by acburdine** [comment]
@stevesc did you end up pushing the `dist` folder to heroku or the main folder?

**Comment by steveszc** [comment]
I pushed up the entire repo and ran `npm start` (`denali server`). I didn't notice any prod-specific instructions in the docs but maybe I didn't look close enough.

**Comment by davewasmer** [comment]
Hmm. So it works locally, but not on Heroku?

I assume the code you are describing is an app you generated and then tried to deploy? Could you try poking around the dyno to confirm that the compiled code is being generated? I.e. that `dist` exists on the server after you run either `denali server` or `denali build`

**Comment by steveszc** [comment]
Okay so looks like Heroku is set up to run `npm start` which in turn runs `node -v && denali server` but a dist ever actually gets built in the dyno. I tried adding a `"postinstal"l: "denali build"` but that didn't seem to help.
