### ISSUE TITLE
Investigate using yargs for arg parsing

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#238]
Right now we parse arguments manually for the CLI. It looks like [yargs](https://github.com/yargs/yargs) might do what we need there, which would mean we could drop a bunch of that code.

**Comment by knownasilya** [comment]
yargs also handles commands, any thoughts on that?

**Comment by davewasmer** [comment]
Yea, sorry, I should have been more clear - I meant use yargs to parse the entire process.argv invocation, including what Denali currently calls the "command", "flags", and "params"

**Comment by davewasmer** [comment]
Other options worth investigating:

* [command](https://github.com/tj/commander.js)
* [argparse](https://github.com/nodeca/argparse)

**Comment by knownasilya** [comment]
Also there is https://github.com/calvinmetcalf/ltcdr which is a fork of commander and would be easier to make changes to if needed.

**Comment by davewasmer** [comment]
Yargs it is! In use in denali-cli now
