### ISSUE TITLE
`denali addon` command doesn't check for passed name

### ISSUE THREAD

**Issue by acburdine** [denali-js/denali#244]
When you run `denali addon`, and fail to pass a "name" argument, denali tries to generate an addon in the directory you're currently in - and then fails when it tries to use `name` in a blueprint template. Running `denali addon <addon-name>` works correctly.

Expected behavior: The command should probably either error if a name is not passed, or prompt for one?

**Comment by davewasmer** [comment]
Should probably error out. The WIP [denali-cli project](https://github.com/denali-js/denali-cli) uses yargs to parse arguments, which should make this relatively trivial.

**Comment by davewasmer** [comment]
Addon command has been removed for now from denali-cli. PRs to reinstate it are welcome (I just dropped it to save some time during the CLI extraction project, since it's not like there's a ton of addon authors yet :wink:)
