### ISSUE TITLE
Ease access for other devs by adding a Slackin integration

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#255]
Right now folks have to get a manual invite to get into our Slack room, it's not the friendly way we're hoping to have Denali feel.

Let's set this up:
https://github.com/rauchg/slackin

**Comment by davewasmer** [comment]
https://denali-slack.now.sh/

**Comment by knownasilya** [comment]
Probably want to add a badge/link to the readme.

**Comment by davewasmer** [comment]
PR's welcome :wink:
