### ISSUE TITLE
Guides say to install denali instead of denali-cli

### ISSUE THREAD

**Issue by rtablada** [denali-js/denali#282]
The current documentation is telling users to install `denali` instead of `denali-cli`.

After talking to @davewasmer in slack, this is likely caused by a break in the CI build for the docs.

<img width="1440" alt="screen shot 2017-03-13 at 12 26 24 pm" src="https://cloud.githubusercontent.com/assets/2532004/23876884/8d6683d0-080d-11e7-8a57-24404b6da86a.png">

**Comment by knownasilya** [comment]
Looks like the issue was here: https://travis-ci.org/denali-js/denali/jobs/210427387#L362

**Comment by davewasmer** [comment]
Looks like the guides manifest was out of date. I improved the error messaging for this scenario (it will warn you the manifest is out of date now), and fixed the manifest itself.
