### ISSUE TITLE
Investigate using node-config

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#286]
Right now our config story is fairly basic - `config/environment.js` plus (broken) `.env` support.

The challenge is that we want to support simple deployment use cases, i.e. "I just git push my app to Heroku", all the way through complex cases, i.e. "I manage my own multi-AZ, HA, VPC server fleet running Kubernetes with a couple snowflakes as well".

The ideal solution would start out simply, and scale up. node-config looks like a good contender.

**Comment by davewasmer** [comment]
So this is unfortunately a bit more problematic than I was hoping.

node-config seems to take the opinionated approach. Rather that simply encapsulating the "load these files in this order, plus env vars, etc" functionality, it wants to run the show. This makes things tough for Denali, which has plenty of opinions of it's own.

The biggest showstopper is that addons need the ability to affect their consuming app's configuration, and node-config seems designed to prevent exactly that. The best it offers is [util.loadFileConfigs](https://github.com/lorenwest/node-config/wiki/Using-Config-Utilities#loadfileconfigsdirectory), which lets us load any directory as if it was the main config directory. But this just gives us an object that is the result of running node-config against that directory. This falls short of the current implementation, which gives the app config to each addon, giving them the chance to mutate the config.

While this child-mutating-parent seems odd at first, I think it could enable all kinds of interesting functionality. A trivial example: imagine an addon that integrates support for Hasicorp's Vault. It might want to scan the _entire_ app config and modify / inject values based on leased secrets extracted from Vault. Of course this requires addons to be "good citizens" and not troll the app config, but in my experience that kind of behavior is relatively rare.

I also don't love the env var implementation - basic Heroku style deployments would require a special `custom-environment-variables.json` mapping file to map the flat env var names to node-config's nested object structure.

**Comment by acburdine** [comment]
we ended up using [nconf](https://github.com/indexzero/nconf) in Ghost's new 1.0 configuration setup, and it seems to work pretty well. It's not as structured as node-config, which makes it much more flexible.

**Comment by davewasmer** [comment]
@acburdine is there anything in particular you like about nconf that isn't present in our current config loading approach (assuming we fix `.env` files)?

**Comment by davewasmer** [comment]
Closing this for now, going to stick with our existing approach + moving dotenv to the CLI. Happy to revisit if anyone has some specific wants/needs that our current approach isn't ideal for, but I'd rather move forward with what's working for now rather than ruminate forever on the perfect approach.
