### ISSUE TITLE
New container model doesn't allow for constructor time logic

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#311]
Because the container is injected after instantiation, any overridden constructor functions won't have access to the container and will appear broken (including all injections).

I think we need to bite the bullet and take over the constructor function signature, and pass in the container (and possibly injections as well) into the constructor.

A couple thoughts:

- Can we still allow for extra constructor args? Does that even make sense? Or will all `new Foo()` calls be made inside the framework so it's not needed?
- If so, we should figure out if we can provide intelligent error messages for cases where the user hacks around and tries to `new Foo()` themselves

**Comment by acburdine** [comment]
FWIW, we already take over instantiation of most container classes via the factory builder, and that doesn't allow passing of any constructor params to the instance as of now: https://github.com/denali-js/denali/blob/master/lib/metal/container.ts#L205 . So in a sense we're already taking over the constructor function signature by not allowing any args to be passed in for most `lookup` calls.

One of the things to consider with this as well is how it would interact with the Babel class-properties transform, specifically because all of the actual injections (e.g. what is returned from denial's `inject` utility) aren't available until after the constructor method anyways. This would potentially cause problems with child classes that override the constructor, because you'd essentially end up (after babel) with:

```js
const { SomeDenaliBaseClass, inject } = require('denali');

module.exports = class MyOverrideClass extends SomeDenaliBaseClass {
    constructor() {
        super(...arguments);
        // try to do stuff with injected stuff here

        // Babel adds class properties here
        parser = inject('parser:xyz');
        anotherthing = inject('anotherthing');
    }
};
```

So essentially we'd have to find some way around that as well.

**Comment by davewasmer** [comment]
Actually, it looks like you are partially correct @acburdine (with your pre-edit comment). It looks like instance properties defined on a _subclass_ are not available in the parent class constructor, [at least with Babel](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=stage-0%2Cstage-1%2Cstage-2%2Cstage-3&targets=&browsers=&builtIns=false&debug=false&code=class%20Foo%20%7B%0A%20%20bar%20%3D%20true%3B%0A%20%20constructor()%20%7B%0A%20%20%20%20console.log(this.bar%2C%20this.buzz)%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Fizz%20extends%20Foo%20%7B%0A%20%20buzz%20%3D%20true%3B%0A%20%20constructor()%20%7B%0A%20%20%20%20super()%3B%0A%20%20%20%20console.log(this.bar%2C%20this.buzz)%3B%0A%20%20%7D%0A%7D%0A%0Anew%20Fizz()).

So if your parent class does something like this:

```
class Action {

  parser = null; // overridden by child class

  constructor() {
    // parser is null here, even if child class overrides with different value and properly calls super
  }

}
```

I'm guessing this is in line with the spec and not an implementation bug, since Babel's transpiled code behaves the same way whether you are transpiling down to ES3 or ES5 (i.e. with or without native class syntax in the transpiled output). Typescript too.

That's a bummer, since it seems like it won't be easy to support abstract base classes that rely on subclass instance properties (at least if the base class needs that property at constructor time).

**Comment by acburdine** [comment]
Given that, it almost seems like doing anything extra is unnecessary at this point? If someone wants to override the constructor it should be fine since we actually don't _do_ anything with the constructor itself, and we won't be able to support container injections in the constructor regardless because of spec. So essentially, we're back to what we have now currently.

**Comment by davewasmer** [comment]
Not quite. The current situation basically doesn't allow for _any_ initialization logic that needs the container. That's a pretty big limitation. And it even fails in very confusing ways - you can see injected properties, but their values are these strange internal placeholder objects, rather than the injected values you'd expect.

The new solution of injecting in the base DenaliObject constructor would allow initialization logic to use injected values and the container. The only exception is if that injected value was defined in a sub-class, which is more of a language limitation than a framework one. 

I suppose decorators could potentially resolve this limitation (by allowing us to expose a list of the injected values on the prototype, so we could analyze and inject the prototype without waiting for an instance to be constructed, thus working around the language limitation of instance properties not being defined before the super class constructor is called). But unfortunately decorators are still not implemented in Babel, which is a pretty big roadblock to using them in any official capacity.

cc @knownasilya (cause I mentioned decorators lol)

**Comment by knownasilya** [comment]
They are implemented in TypeScript though right? Not sure how that works.

**Comment by davewasmer** [comment]
Yep, implemented in TS - but I don't want Denali to become a Typescript Framework™. If there isn't general support for a language level feature, I don't want to ship core functionality that requires that feature. Of course, we can use those features as sugars over core supported syntax, but it can't be _required_.

**Comment by knownasilya** [comment]
I agree.

**Comment by davewasmer** [comment]
Crap. Just realizing this won't work. I was focused on user code that might want to access the injected values in a constructor function - but the same restrictions apply to Denali itself, obviously. Which means that our base DenaliObject constructor, which was going to apply injections, won't see any of the injections defined in the user's subclass. So no injections work anywhere (this is why the tests are failing now).

So, I think our only option left is to go back to applying the injections after creating the instance. We can then invoke an `init()` hook to give the user the ability to run constructor-ish time logic. I don't love adding more complexity to mimic what ideally would be standard language features, but I don't see a way around this one ...

**Comment by davewasmer** [comment]
We now have an init() hook
