### ISSUE TITLE
Inject logger everywhere

### ISSUE THREAD

**Issue by seawatts** [denali-js/denali#312]
It is a little inconvenient to have to inject the logger whenever you want to use it.

It would be nice if the logger was already injected in every container object.

**Comment by davewasmer** [comment]
What about just injecting into all actions by default? I'm very hesitant to inject it _everywhere_ for containered objects - it's easy to imagine some use case where either the injection would clobber an existing `this.logger`, or the local `this.logger` would clobber the injected value, resulting in a surprise when the interface is different.

If your application has a custom container type (i.e. `app/slack-commands/`), you could inject the logger once into a base `SlackCommand` class that all your `app/slack-commands/*` inherit from.

**Comment by davewasmer** [comment]
Moving this to backlog pending response. Happy to bump it back up once we can reach consensus on whether or not we want to inject the logger _everywhere_. In the meantime, I've added it to the base Action class.

**Comment by davewasmer** [comment]
Closing this for lack of response. We can reopen if anyone wants to chime in for why we should inject everywhere.
