### ISSUE TITLE
Update blueprints to use orm-adapter/application.js instead of ormAdapter config property

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#320]
The application always uses the MemoryAdapter, since that seems to be the default if none are found.

**Comment by rv-aburdine** [comment]
FWIW, I came across this after playing with the recent container refactor and found the same thing. However, after conversation with @davewasmer the intent was to move away from specifying the ormAdapter in config and instead declaring an ApplicationOrmAdapter that extends whichever one you want, which makes it align more with the other first-class concepts in Denali (serializers, parsers)

**Comment by knownasilya** [comment]
Makes sense. So the blueprints need updating.

**Comment by davewasmer** [comment]
I updated the issue title to reflect @acburdine's comment.
