### ISSUE TITLE
Missing data escape hatches

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#321]
I might be wrong, but these are some thoughts:

1. Allowing to fetch simplified data of a model
   - Select which attributes are returned, e.g. id and name
   - At the db level, since a model might have many attributes, and fetching them all and then limiting at the serializer might be too slow
2. Override default fetch methods
   - Use case, a model is made up of three tables and needs a join
   - Other models behave with a single table
   - This seems possible since we now extend the adapter directly
3. Add custom fetch methods that do something specific
   - Do these go on the model directly as static methods, and get exposed via the `db` service?
   - Seems like it would need to be defined on the model, and then exposed through the db service. Throw for models that don't have it?

**Comment by davewasmer** [comment]
Great stuff @knownasilya! Some comments/responses:

> Allowing to fetch simplified data of a model
> - Select which attributes are returned, e.g. id and name
> - At the db level, since a model might have many attributes, and fetching them all and then limiting at the serializer might be too slow

We definitely need to allow for this, but it feels like a concern for the ORM. I'm not sure we want Denali incorporating this kind of functionality.

My thought is that, from the Denali side of things, `this.db.query` would likely end up being the escape valve for most things - the adapter can decide the semantics, and I imagine most would allow some kind of query building callback to be passed in.

So, for example, let's say you want to return a subset of fields (i.e. `SELECT foo, bar ...`) and you are using the `denali-objection`/Objection.js ORM as an example (note: this may not work in the current version of `denali-objection` - it's just to demonstrate):

```
this.db.query('post', (postQuery) => {
  return postQuery.select([ 'foo', 'bar' ]);
});
```

I think the key point here is that Denali has no understanding of the query arguments passed in.

> Override default fetch methods
> - Use case, a model is made up of three tables and needs a join
> - Other models behave with a single table
> - This seems possible since we now extend the adapter directly

Hm - I again want to be careful about what assumptions we bake into Denali about the behavior of the ORM. Every additional assumption is potentially a limitation for some crazy database/ORM that someone wants to use.

My gut would say that this is again the realm of the ORM. If your ORM cannot support something like a model backed by multiple tables, I would be very wary of hacking Denali's ORM layer to add that support. It might work, but I suspect you'd quickly run into obstacles.

> Add custom fetch methods that do something specific
> - Do these go on the model directly as static methods, and get exposed via the db service?
> - Seems like it would need to be defined on the model, and then exposed through the db service. Throw for models that don't have it?

Do you have an example? I suspect these use cases could be covered by `this.db.query` but perhaps I'm wrong.

-----

FWIW, I've occasionally toyed with the idea of _really_ stripping down the ORM layer to the point that only addons would really use the Denali-defined data APIs. The whole goal of the ORM adapter layer is to allow for addons to perform data operations without needing to know which database/ORM you are using.

I think there's enough benefit to keeping the ORM layer as is, but I'm worried that this will be a continual stumbling block for new learners: it's totally expected to use lots of ORM specific syntax in your app. Really, the query aspects of Denali are mostly sugar over `this.db.query` for some more common operations.

**Comment by knownasilya** [comment]
> My thought is that, from the Denali side of things, this.db.query would likely end up being the escape valve for most things - the adapter can decide the semantics, and I imagine most would allow some kind of query building callback to be passed in.

I like that solution.

> Do you have an example? I suspect these use cases could be covered by this.db.query but perhaps I'm wrong.

I agree that `this.db.query` makes sense here, but if you reuse a certain query quite a bit, how would that be made into a reusable function. Or where?

**Comment by davewasmer** [comment]
> if you reuse a certain query quite a bit, how would that be made into a reusable function. Or where?

There's no first class concept for that in Denali (nor should there be IMHO). I'd suggest an `app/utils` or `app/queries` folder perhaps.

**Comment by knownasilya** [comment]
Even though there is no code concept, we need something in the guides I think to guide users.
