### ISSUE TITLE
Single step install

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#339]
Right now users must install `denali` and `denali-cli` globally, which is a bit surprising.

Let's make whatever changes are needed to ensure that users can just `npm install -g denali-cli` and get going.

To that end, we need to move all commands that run outside an app to the CLI project. That means `denali new` and `denali generate addon` (should become `denali addon`). Along with their supporting files (i.e. `CommandAcceptanceTest`).

- [ ] Move `new` command to CLI
  - [ ] Move `app` blueprint to CLI
  - [ ] Move `denali new` tests to CLI
- [ ] Move `generate addon` command to CLI
  - [ ] Move `addon` blueprint to CLI
  - [ ] Move `denali generate addon` tests to CLI
- [ ] Move `BlueprintAcceptanceTest` to CLI
- [ ] Move `CommandAcceptanceTest` to CLI

**Comment by acburdine** [comment]
Relevant denali-cli PR: https://github.com/denali-js/denali-cli/pull/24
