### ISSUE TITLE
Add destroy hook to DenaliObject

### ISSUE THREAD

**Issue by seawatts** [denali-js/denali#351]
Would be nice to have a respective destroy command on the DenaliObject, like init. This could be useful during testing.

**Comment by seawatts** [comment]
https://github.com/denali-js/denali/blob/master/lib/runtime/application.ts#L260

**Comment by davewasmer** [comment]
So we could do this for _some_ types of objects right now, but not for all without some changes. Basically we could do this for anything in the container that is a singleton. But for things like actions, those are tied to the lifetime of a single request, so there is "destroy" event, they eventually just lose all references and get GC'd.

Is that what you had in mind? Do you have a specific use case you need this for?

**Comment by seawatts** [comment]
I have a bot running that opens up a web socket. And then for each acceptance test it ends up keeping those websockets open between tests which causes it to fail. So it would be nice to be able to close those sockets every time a test finishes

**Comment by davewasmer** [comment]
Are you managing those sockets via a service?

**Comment by seawatts** [comment]
Yes
