### ISSUE TITLE
Using `test.before` and others with context.app

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#352]
The following doesn't work

```js
appAcceptanceTest(test);

test.before((t) => {
  t.context.app.setHeader('content-type', 'application/vnd.api+json');
});
```

The `t.context.app` is `undefined`.

**Comment by davewasmer** [comment]
You probably want to use before each here. The app is generated in a before each so it's fresh for each test.

**Comment by knownasilya** [comment]
Would the `context.app` exist in `test.beforeEach`? Seems like I'd run into the same issue.

**Comment by davewasmer** [comment]
It should, as long as you put your `test.beforeEach` after the `appAcceptanceTest(test)`.

**Comment by davewasmer** [comment]
Closing for now, feel free to reopen if the issue persists even after ensuring the right ordering of method calls.
