### ISSUE TITLE
How to use as a git dep?

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#356]
Right now, denali addons are published from their dist folder. This is nice because it avoids shipping the entire source code with every npm install, and keeps your node_modules folder simpler.

However, this is a problem when using a git dependency. npm will clone the git repo, resulting in the compiled addon existing one directory down (where denali won't look for it) or not existing at all (because the addon author didn't check in the compiled source).

I'd love to find a middle ground here that satisfies both use cases - so we don't have to ship/download the entire source for every addon each time, but also so that they work as git deps.

Some thoughts off the top of my head:

1. Does npm treat git deps differently in any way after they are installed?
2. What do other tools do? Certainly there must exist some package that is compiled from source and could potentially be installed via git dep.

**Comment by seawatts** [comment]
What about having denali check to see if it is a built dependency. If not build it and use the dist folder otherwise just use the already built code.

**Comment by davewasmer** [comment]
Closing in favor of denali-js/denali-cli#31
