### ISSUE TITLE
Allow container customization based on environment

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#361]
We should allow users to swap container entries based on environment, i.e. in test, use the memory adapter, in dev and prod use my foo adapter. Right now this only seems possible via initializers, which is a little too heavyweight & unintuitive.

**Comment by knownasilya** [comment]
Yes, please! Tests, Mirage style with an in-memory adapter would be nice!

**Comment by davewasmer** [comment]
So far, the only idea I have is providing the `container` to your `config/environment.js` file, so you could do something like:

```
if (environment === 'development') {
  container.register('orm-adapter:application', MemoryAdapter)
}
```

The problem here is if you have model-specific orm adapters you'd need to override each one with a `container.register('orm-adapter:<model name>')`. Overriding the ApplicationAdapter wouldn't work, because when you subclass to create the PostAdapter, you statically import rather than use the container. 😕

**Comment by knownasilya** [comment]
Can denali add the container after static creation?

**Comment by davewasmer** [comment]
Another approach as well as challenge here is to think about how to handle retrieved files in an environment specific way.

There's two ways the container looks up an entry: by registry or by file. The registry is manually populated via `container.register()` and takes precedence. Otherwise, it falls back to a file-based lookup (`model:post` -> `app/models/post.js`).

One way to support environment specific changes to the container might be to use filename based differentiation, i.e.:

```
app/orm-adapters/application.js
app/orm-adapters/application.test.js
app/orm-adapters/application.production.js
```

**Comment by knownasilya** [comment]
That's not a bad idea. Kind of looks a bit like some of the module unification stuff from Ember.

**Comment by davewasmer** [comment]
Thinking through this some more - I'm not sure we need a super robust solution here. Unfortunately, I think pretty much all non-trivial apps wouldn't be able to use the in-memory adapter in test mode, since they'll use queries that are ORM specific, which would fail if you swap out the ORM adapter.

With that in mind, I can't think of any other strong use cases right now for loading different files via the container based on the environment. So I think exposing the container to the config function should be sufficient.
