### ISSUE TITLE
Include standard-version as part of denali publish

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#364]
Currently, you have to do test, then `standard-version`, then `denali publish`.

This could be wrapped into one, with an additional `--skip-versioning` flag.

**Comment by acburdine** [comment]
Something to keep in mind for this is that the flags for standard-version would need to be added to `denali publish` as well.

**Comment by davewasmer** [comment]
Duplicate of #298

**Comment by knownasilya** [comment]
Ops 👍
