### ISSUE TITLE
Move request body parsing into Parser's responsibilities

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#372]
The lack of control over the incoming request body parsing is becoming problematic. I.e. the default app blueprint doesn't work out of the box, because we need to specify the JSONAPI media type to the body parser middleware.

Since the Parser class is responsible for understanding the shape of the incoming request, it should be responsible for buffering/parsing the JSON too. This would also allow for first-class implementations of streaming parsers, file uploads, etc.

The open question is how to handle middleware that need the buffered and parsed request body. One suggestion from @willviles that I like was that we use this rule as a good answer to "does my middleware belong in `config/middleware.js` or as an action filter?" If it needs the request body parsed, it belongs in Denali-land (i.e. a before filter on ApplicationAction). If not, i.e. if it's low level operations on the req/res objects, then `config/middleware.js` it is.

**Comment by seawatts** [comment]
Can this be closed now?
