### ISSUE TITLE
Add better DX around passing in null or undefined mixins

### ISSUE THREAD

**Issue by seawatts** [denali-js/denali#373]
Currently https://github.com/denali-js/denali/blob/6e383b73ea353ecf2fe41fc2cd035db46b72972c/lib/metal/mixin.ts#L44 blows up if it is null or undefined. We should do a check before we get here and tell the developer that you are not passing in the correct mixin

**Comment by davewasmer** [comment]
Duplicate of #229 - but thanks for filling, and wholeheartedly agree.
