### ISSUE TITLE
Is there any desire for denali models compatible with ember data ones?

### ISSUE THREAD

**Issue by QuantumInformation** [denali-js/denali#393]
Ie so I can copy paste or share code about?

**Comment by davewasmer** [comment]
Depends on what you mean by compatible :wink:

A couple points to consider:

1. I don't want to tie the Denali Model interface to _any_ frontend framework's model interface. The server is a fundamentally different place, and limiting ourselves to whatever the Ember Data team decides for their interface is asking for trouble down the line. So, in a strict, "I can literally copy/paste my Denali model into my Ember app" sense, the answer is "no". That is not the goal. It might be accidentally possible at some point if we happen to pick similar names for methods, etc, but we won't design Denali with that aim in mind.

2. That said, I'd love to have a good story around aligning frontend data models (not just ember data) with Denali's data models. I think that's a common busywork task that would be ideal to automate.

With (2), I'm hesitant to limit that story to Ember Data only, especially if there's any part in core. Denali is meant to be agnostic to the frontend, and incorporating features specific to a particular framework, however useful, might confuse potential users into thinking "oh, Denali is that Ember backend framework".

Instead, I think the right balance here is to ensure that Denali Model's are easily statically analyzed, and then potentially release a separate module(s) that would analyze a Denali project, extract the Model schema/metadata, and transform it into [insert frontend framework] model code.

To illustrate this more concretely, here's an example of how this might work for Ember:

* You install the `ember-cli-denali-model-sync` addon into your Ember app
* That addon exposes a CLI command (`$ ember sync-denali-models ../path/to/denali/project`) that you run to sync the Ember frontend models with your backend Denali models
  * That command would leverage the `denali-extract-model-schema` package  to extract the relevant schema from a Denali project
  * It would take that extracted schema, apply some Ember-specific transformations to it, and write it out as Ember Data Models in your local Ember app.

This process could be duplicated for React, Vue, or whatever the new hotness is in frontend-land, only changing the frontend framework specific parts (i.e. how to ship the command, what transformations are needed).

**Comment by QuantumInformation** [comment]
Your proposed solution seems optimal to me.
