### ISSUE TITLE
Docs site broken

### ISSUE THREAD

**Issue by justsml** [denali-js/denali#426]
Site looks really good. Except for one thing...

I get 404's navigating any sub page:
 
![image](https://user-images.githubusercontent.com/397632/36067548-58f366c4-0e7c-11e8-94d9-34c9d309d4d2.png)

**Comment by davewasmer** [comment]
@justsml heh - you caught us in the middle of a transition between sites. Unfortunately, the current site is, as you discovered, unfinished. I plan to have things ironed out and the docs updated by the end of this week though, so stay tuned and check back in!
