### ISSUE TITLE
Auth addon

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#60]
Need a cohesive story for auth. Should be simple out of the box, and could serve as a good test case / example addon

**Comment by acorncom** [comment]
@davewasmer Do you have additional thoughts / guidance here?  This would be the next piece I'd need for the ember-help-wanted-backend after I get the webhook piece built ...

**Comment by davewasmer** [comment]
This is [my first stab](https://github.com/denali-js/denali-auth) at it so far, but it's pretty outdated. I was planning on looking at Passport.js and Devise for inspiration. I'd like this to be an "official" addon, a la Ember Data for Ember.

**Comment by davewasmer** [comment]
Closing in favor of the [org-wide project tracking the 0.1.0-beta.1 release](https://github.com/orgs/denali-js/projects/1).

Also, denali-auth now has a fleshed out first-pass implementation!
