### ISSUE TITLE
Initial linting has errors & security vulnerabilities unclear

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#71]
```sh
iradchenko app (master)$ denali server
Linting failed:

/Users/iradchenko/battleground/app/config/environment.js
✖ 4 problems (4 errors, 0 warnings)


/Users/iradchenko/battleground/app/config/environment.js
  1:16  error  Missing JSDoc comment          require-jsdoc
  4:13  error  Unexpected use of process.env  no-process-env

/Users/iradchenko/battleground/app/config/middleware.js
  1:16  error  Missing JSDoc comment  require-jsdoc

/Users/iradchenko/battleground/app/config/routes.js
  1:16  error  Missing JSDoc comment  require-jsdoc

✖ 4 problems (4 errors, 0 warnings)

Build completed in 0.281s
[2016-07-30T00:18:30.653Z] INFO - app@0.0.1 server up on port 3000
WARNING: Some packages in your package.json may have security vulnerabilities:
[object Object] 0 [object Object],[object Object],[object Object],[object Object]
[object Object] 1 [object Object],[object Object],[object Object],[object Object]
[object Object] 2 [object Object],[object Object],[object Object],[object Object]
[object Object] 3 [object Object],[object Object],[object Object],[object Object]
```

I tried to debug the security issue, but as I mentioned I couldn't get normal debugging working.

**Comment by davewasmer** [comment]
The linting errors should be fixed - I dropped the rules from `eslint-config-denali`. Those were meant to apply to the `denali` repo itself, but are probably too strict to assume for consuming apps.

That, plus #73, means that this should be resolved (I think). Closing for now, but feel free tor reopen if I missed something.

**Comment by davewasmer** [comment]
Derp - the security vulnerabilities are still there ...

**Comment by knownasilya** [comment]
Can we close this, since the maildev is gone now?

**Comment by davewasmer** [comment]
I'm still getting the errors - I'm guessing NSP looks at denali's published package.json rather than what's on disk. I'll close when I publish a new version and confirm the errors disappear (I'll probably push something out today).
