### ISSUE TITLE
Clean up deps/devDeps

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#78]
In Denali's package.json, as well as the app/addon blueprint package.json, we probably need to move some of the devDeps out to regular deps (see [this comment](https://github.com/denali-js/denali/commit/b0a4f058bec8451508f3013c88ef4f6905888236#commitcomment-18658927)). There also appears to be some duplicates in the app/addon blueprints.

**Comment by acorncom** [comment]
We're getting a warning about mocha existing as a dep and a devDep post https://github.com/denali-js/denali/commit/9dc785e41856af75e77583769bb08c89eb82f0a3

**Comment by knownasilya** [comment]
Seems like it should just be a dep, since it's used in the test command.
