### ISSUE TITLE
Support sockets

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#79]
I think socket support is a must have for any ambitious framework, since it would probably be the deciding factor to use Denali for anyone needing them or thinking that they would in the future.

Also, it's an opportunity to shine, since socket code is usually more cluttered then router code, so if we can have a convention around sockets as well, all the better.

**Comment by davewasmer** [comment]
💯 

Yea, we'll definitely need to support sockets at some point. A quick brain dump of some of my thoughts on this so far:

## Don't "unify" transports by default

I'm generally not a fan of the Sails.js style approach where controller actions can be reached by HTTP or socket connections, and the framework abstracts that away. 

The framework should certainly allow for that, but the idea that most of your socket code is identical to HTTP handling code seems like a bad assumption to me. Sockets have fundamental differences from the standard HTTP req/res paradigm, and abstracting away those differences just results in a lowest common denominator of HTTP & sockets, without any of the strengths of either transport.

## We need to find the right primitives

Denali's Actions are a fundamental primitive that enables building extensible and robust HTTP endpoints. In the same fashion, we need to think through what the fundamental primitives of a socket server would be.

Unfortunately, I don't have a ton of experience with production apps that use sockets extensively. From what I can see looking at other frameworks, a Channel might be a candidate for that low level primitive, but I'm not sure.

Ideally, we could find a primitive that enables building more complex / opinionated abstractions on top. In the same way that Actions can be composed into more complex addons (i.e. denali-auth), I'd like to see socket primitives composable into more complex structures.

## Multiple primitives?

Perhaps a good solution might involve multiple primitives for different use cases? I.e. we could take the "unified transport" approach mentioned above (i.e. the client can reach any action via HTTP or sockets), but then offer another primitive (i.e. Channels) for use cases that lean of the unique bi-directional / realtime nature of sockets?

-----

So, I think our next step here is to identify what some common use cases are for sockets. From there, we can hopeful come up with a good primitive, with stories for how the use cases are satisfied. Then we can get into the weeds of specific implementation details.

I put up a [wiki page](https://github.com/denali-js/denali/wiki/Socket-Architecture-Brainstorm) detailing this - feel free to add any of your own thoughts too. I figure that can be a home base for the current state of our planning.

**Comment by davewasmer** [comment]
Closing in favor of http://discuss.denalijs.org/t/sockets-realtime-support/29
