### ISSUE TITLE
Tests don't work

### ISSUE THREAD

**Issue by tomdale** [denali-js/denali#82]
Running `npm test` does not actually run any tests. Travis reports success because it is [running zero tests](https://travis-ci.org/denali-js/denali/builds/158167229).

**Comment by knownasilya** [comment]
Thank you! They should run now, but don't pass yet (slightly outdated).

**Comment by davewasmer** [comment]
Shucks, I was hoping no one would notice :trollface:

**Comment by davewasmer** [comment]
They're passing! Lots more coverage needed though ...
